from alns.criteria import HillClimbing

DEPOT = -1
TEAM_NUMBER = 3
DEGREE_OF_DESTRUCTION = 0.25
MIN_QUANTITY_SAMPLE_SHAPE = 0.35
WEIGHTS = [25, 5, 1, 1]
DECAY = 0.8
CRITERION = HillClimbing()
ITERATIONS = 100
